import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hooks</h1>

        <p className={styles.description}>
          Get started by navigating to the following links:
        </p>

        <div className={styles.grid}>
          <a href="/react-hooks/use-state" className={styles.card}>
            <h2>useState &rarr;</h2>
          </a>

          <a href="/react-hooks/use-effect" className={styles.card}>
            <h2>useEffect &rarr;</h2>
          </a>

          <a href="/react-hooks/use-ref" className={styles.card}>
            <h2>useRef &rarr;</h2>
          </a>

          <a href="/react-hooks/use-reducer" className={styles.card}>
            <h2>useReducer &rarr;</h2>
          </a>
          <a href="/react-hooks/use-layout-effect" className={styles.card}>
            <h2>useLayoutEffect &rarr;</h2>
          </a>
          <a href="/react-hooks/use-memo" className={styles.card}>
            <h2>useMemo &rarr;</h2>
          </a>
          <a href="/react-hooks/use-imperative-handle" className={styles.card}>
            <h2>useImperativeHandle &rarr;</h2>
          </a>
          <a href="/react-hooks/use-context" className={styles.card}>
            <h2>useContext &rarr;</h2>
          </a>
          <a href="/react-hooks/use-callback" className={styles.card}>
            <h2>useCallback &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
